### PR TITLE
Test fixes, package version updates

### LINKED ISSUE #252: [TASK] Remove all Fixed Anchor references and update tests accordingly
## Overview

We are deprecating the fixed anchor and should remove all unnecessary code from this repo that references anchor. Tests will need to be updated and fixed accordingly. 

### Tasks

- [ ] Remove all fixed anchor references
- [ ] Update tests that utilize fixed anchor

### PR DESCRIPTION
**Pull request by drewstone**
Closes #252  #256

### CODE REVIEW

File: packages/wasm-utils/src/utxo.rs [hunk 1]
```diff
@@ -93,7 +93,7 @@ impl JsUtxo {
 
 	pub fn get_chain_id_bytes(&self) -> Vec<u8> {
 		match &self.inner {
-			JsUtxoInner::Bn254(bn254_utxo) => bn254_utxo.chain_id.into_repr().to_bytes_le(),
+			JsUtxoInner::Bn254(bn254_utxo) => bn254_utxo.chain_id.into_repr().to_bytes_be(),
```
Comment (drewstone) [inline packages/wasm-utils/src/utxo.rs:96]: We should use the method on the `u64` type instead, since we also have an implementation for getting the raw value.

```
pub fn get_chain_id_bytes(&self) -> Vec<u8> {
        self.get_chain_id_raw().to_be_bytes()
}
```

**Review by AhmedKorim — APPROVED** [review]

File: packages/wasm-utils/src/utxo.rs (hunk 1 above)
Comment (AhmedKorim) [reply packages/wasm-utils/src/utxo.rs:96]: This didn't work well with the proof generation
